apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      name: laravel-app
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: swr.ap-southeast-3.myhuaweicloud.com/lcs-test/laravel-app:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: default-secret